development:
  adapter: postgresql
  encoding: unicode
  database: spiria_bbq_development
  pool: 50
  username: test
  password: test
  host: localhost
test:
  adapter: postgresql
  encoding: unicode
  database: spiria_bbq_test
  pool: 5
  username: test
  password: test
  host: localhost
